services:
  - type: web
    name: makemyfinance-backend
    env: python
    rootDir: backend
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: python manage.py migrate && gunicorn item_service.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: DJANGO_SETTINGS_MODULE
        value: item_service.settings
      - key: DEBUG
        value: "False"
