# """
# Django settings for item_service project.

# Generated by 'django-admin startproject' using Django 5.2.4.

# For more information on this file, see
# https://docs.djangoproject.com/en/5.2/topics/settings/

# For the full list of settings and their values, see
# https://docs.djangoproject.com/en/5.2/ref/settings/
# """

# from pathlib import Path

# # Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent


# # Quick-start development settings - unsuitable for production
# # See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# # SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-#(y=^h8t05g=d_y7s^(i_k_p-*8d#)&deo3+c9cs#p2we8ry!n'

# # SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True

# ALLOWED_HOSTS = []


# # Application definition

# INSTALLED_APPS = [
#     'django.contrib.admin',
#     'django.contrib.auth',
#     'django.contrib.contenttypes',
#     'django.contrib.sessions',
#     'django.contrib.messages',
#     'django.contrib.staticfiles',
#     'rest_framework',
#     'api',
#     'corsheaders',
#     'rest_framework_simplejwt.token_blacklist',
# ]

# MIDDLEWARE = [
#     'django.middleware.security.SecurityMiddleware',
#     'corsheaders.middleware.CorsMiddleware',
#     'django.contrib.sessions.middleware.SessionMiddleware',
#     'django.middleware.common.CommonMiddleware',
#     'django.middleware.csrf.CsrfViewMiddleware',
#     'django.contrib.auth.middleware.AuthenticationMiddleware',
#     'django.contrib.messages.middleware.MessageMiddleware',
#     'django.middleware.clickjacking.XFrameOptionsMiddleware',
# ]

# ROOT_URLCONF = 'item_service.urls'

# TEMPLATES = [
#     {
#         'BACKEND': 'django.template.backends.django.DjangoTemplates',
#         'DIRS': [],
#         'APP_DIRS': True,
#         'OPTIONS': {
#             'context_processors': [
#                 'django.template.context_processors.request',
#                 'django.contrib.auth.context_processors.auth',
#                 'django.contrib.messages.context_processors.messages',
#             ],
#         },
#     },
# ]

# WSGI_APPLICATION = 'item_service.wsgi.application'

# # Database
# # https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# from mongoengine import connect
# connect(
#     db='item_db',
#     host="mongodb://localhost:27017/item_db"
# )

# # Password validation
# # https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

# AUTH_PASSWORD_VALIDATORS = [
#     {
#         'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
#     },
# ]


# # Internationalization
# # https://docs.djangoproject.com/en/5.2/topics/i18n/

# LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'UTC'

# USE_I18N = True

# USE_TZ = True


# # Static files (CSS, JavaScript, Images)
# # https://docs.djangoproject.com/en/5.2/howto/static-files/

# STATIC_URL = 'static/'

# # Default primary key field type
# # https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

# DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS_ALLOWED_ORIGINS=["http://localhost:5173"]

# REST_FRAMEWORK = {
#     'DEFAULT_AUTHENTICATION_CLASSES': (
#         'rest_framework_simplejwt.authentication.JWTAuthentication',
#     ),
# }

from pathlib import Path
from mongoengine import connect
from dotenv import load_dotenv
import os
from urllib.parse import quote_plus, urlparse
load_dotenv()

BASE_DIR = Path(__file__).resolve().parent.parent
DEBUG = os.getenv("DEBUG", "False").lower() == "true"
SECRET_KEY = os.getenv("SECRET_KEY", "fallback-secret")


def _csv_env(name):
    return [value.strip() for value in os.getenv(name, "").split(",") if value.strip()]

ALLOWED_HOSTS = _csv_env("ALLOWED_HOSTS")
if not ALLOWED_HOSTS:
    ALLOWED_HOSTS = ["localhost", "127.0.0.1"]


# -----------------------------
# ✅ Installed Apps
# -----------------------------
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'api',
    'corsheaders',
    'rest_framework_simplejwt.token_blacklist',
]

# -----------------------------
# ✅ Middleware
# -----------------------------
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # CORS first
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'item_service.urls'

# -----------------------------
# ✅ Templates
# -----------------------------
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'item_service.wsgi.application'

# -----------------------------
# ✅ Database (Dummy for Django with MongoEngine)
# -----------------------------
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# -----------------------------
# ✅ MongoDB Connection
# -----------------------------
username = os.getenv("MONGODB_USER")
password = quote_plus(os.getenv("MONGODB_PASS"))  # encode special chars (@, #, :)
host = os.getenv("MONGODB_HOST")
db_name = os.getenv("MONGODB_DATABASE_NAME")

MONGODB_URI = f"mongodb+srv://{username}:{password}@{host}/{db_name}?retryWrites=true&w=majority&appName=MakeMy Finance"

try:
    connect(
        db=db_name,
        host=MONGODB_URI
    )
    print("Connected to MongoDB Atlas successfully")
except Exception as e:
    print(f"Failed to connect to MongoDB Atlas: {e}")
# -----------------------------
# ✅ Password Validation
# -----------------------------
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# -----------------------------
# ✅ Internationalization
# -----------------------------
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Kolkata'  # For India
USE_I18N = True
USE_TZ = True

# -----------------------------
# ✅ Static Files
# -----------------------------
STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"

# -----------------------------
# ✅ Default Auto Field
# -----------------------------
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# -----------------------------
# ✅ CORS (Frontend access)
# -----------------------------
CORS_ALLOWED_ORIGINS = _csv_env("CORS_ALLOWED_ORIGINS")
CSRF_TRUSTED_ORIGINS = _csv_env("CSRF_TRUSTED_ORIGINS")
CORS_ALLOWED_ORIGIN_REGEXES = _csv_env("CORS_ALLOWED_ORIGIN_REGEXES")

default_prod_origins = [
    "https://www.makemyfinance.online",
    "https://makemyfinance.online",
    "https://make-my-finance-a-personal-finance.vercel.app",
]
for origin in default_prod_origins:
    if origin not in CORS_ALLOWED_ORIGINS:
        CORS_ALLOWED_ORIGINS.append(origin)
    if origin not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(origin)

default_prod_hosts = [
    "www.makemyfinance.online",
    "makemyfinance.online",
    "makemyfinance-a-personal-finance.onrender.com",
]
for host in default_prod_hosts:
    if host not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(host)

render_external_url = os.getenv("RENDER_EXTERNAL_URL", "").strip()
if render_external_url:
    parsed = urlparse(render_external_url)
    render_host = parsed.hostname
    if render_host and render_host not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(render_host)

    if render_external_url not in CORS_ALLOWED_ORIGINS:
        CORS_ALLOWED_ORIGINS.append(render_external_url)

    if render_external_url not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(render_external_url)

# During local development, include common Vite ports so the frontend at
# localhost:5173 or localhost:5175 can reach this API without CORS errors.
if DEBUG:
    local_origins = [
        "http://localhost:5173",
        "http://127.0.0.1:5173",
        "http://localhost:5175",
        "http://127.0.0.1:5175",
    ]
    for origin in local_origins:
        if origin not in CORS_ALLOWED_ORIGINS:
            CORS_ALLOWED_ORIGINS.append(origin)

# Allow credentials (cookies, auth headers) over CORS if needed by the frontend
CORS_ALLOW_CREDENTIALS = True

if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

# -----------------------------
# ✅ REST Framework Settings
# -----------------------------
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "makemy-finance-auth",
    }
}

SMTP_HOST = os.getenv('SMTP_HOST', os.getenv('EMAIL_HOST', 'smtp.gmail.com'))
SMTP_PORT = int(os.getenv('SMTP_PORT', os.getenv('EMAIL_PORT', '587')))
SMTP_USER = os.getenv('SMTP_USER', os.getenv('EMAIL_HOST_USER', ''))
_raw_smtp_password = os.getenv('SMTP_PASSWORD', os.getenv('EMAIL_HOST_PASSWORD', ''))
# Gmail app passwords are often copied with spaces every 4 chars; normalize before SMTP auth.
SMTP_PASSWORD = (_raw_smtp_password or '').replace(' ', '').strip()
SMTP_FROM_EMAIL = os.getenv('SMTP_FROM_EMAIL', SMTP_USER)

EMAIL_BACKEND = os.getenv(
    'EMAIL_BACKEND',
    'django.core.mail.backends.console.EmailBackend' if DEBUG else 'django.core.mail.backends.smtp.EmailBackend'
)
EMAIL_HOST = SMTP_HOST
EMAIL_PORT = SMTP_PORT
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'true').lower() == 'true'
EMAIL_TIMEOUT = int(os.getenv('EMAIL_TIMEOUT', os.getenv('SMTP_TIMEOUT', '8')))
EMAIL_HOST_USER = SMTP_USER
EMAIL_HOST_PASSWORD = SMTP_PASSWORD
DEFAULT_FROM_EMAIL = SMTP_FROM_EMAIL

AUTH_OTP_LENGTH = int(os.getenv('AUTH_OTP_LENGTH', '6'))
AUTH_OTP_EXPIRY_MINUTES = int(os.getenv('AUTH_OTP_EXPIRY_MINUTES', '10'))
AUTH_OTP_MAX_ATTEMPTS = int(os.getenv('AUTH_OTP_MAX_ATTEMPTS', '5'))
AUTH_RATE_LIMIT_WINDOW_SECONDS = int(os.getenv('AUTH_RATE_LIMIT_WINDOW_SECONDS', '300'))
AUTH_RATE_LIMIT_IP_MAX = int(os.getenv('AUTH_RATE_LIMIT_IP_MAX', '25'))
AUTH_RATE_LIMIT_EMAIL_MAX = int(os.getenv('AUTH_RATE_LIMIT_EMAIL_MAX', '8'))
AUTH_REQUIRE_LOGIN_OTP = os.getenv('AUTH_REQUIRE_LOGIN_OTP', 'true').lower() == 'true'
GOOGLE_API_KEY = os.getenv("GOOGLE_API_KEY")
